"""Frozen public scientific constants used by the spectral and PISD APIs."""

RANDOM_STATE = 42

MIN_FREQUENCY = 0.01
MAX_FREQUENCY = 20.0
SAMPLES_PER_PEAK = 5
FALSE_ALARM_PROBABILITY = 0.01

PEAK_HEIGHT_FACTOR = 3.0
PEAK_PROMINENCE_FACTOR = 2.0
PEAK_WIDTH_RELATIVE_HEIGHT = 0.5
SPECTRAL_EPSILON = 1e-12
USE_RAYLEIGH_PEAK_DISTANCE = True

SPECTRAL_COMPLEXITY_EPSILON = 1e-12
POWER_NEGATIVE_TOLERANCE = 1e-12
TOP_POWER_FRACTION = 0.10
